project:
  type: book

book:
  title: "That's weird! Anomaly&nbsp;detection using&nbsp;R"
  author:
    name: "<a href='https://robjhyndman.com'>Rob J Hyndman</a>"
    affiliation: "Monash University, Australia"
  site-url: "https://OTexts.com/weird"
  chapters:
    - index.qmd
    - "01-intro.qmd"
    - "02-univariate.qmd"
    - "03-multivariate.qmd"
    - "04-tests.qmd"
    - "05-boxplots.qmd"
    - "06-density.qmd"
    - "07-distance.qmd"
    - "08-highdim.qmd"
    - "09-timeseries.qmd"
    - "10-functional.qmd"
    - "11-network.qmd"
    - "12-imagevideo.qmd"
    - "13-text.qmd"
    - "14-distributions.qmd"
    - "15-cybersecurity.qmd"
    - "99-refs.qmd"
  page-footer:
    left: "Published by OTexts using [Quarto](https://quarto.org). {{< fa copyright >}} [Rob J Hyndman](https://robjhyndman.com)"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"
  favicon: "https://otexts.com/favicon.ico"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
include-before-body: google_analytics.html
bibliography: weird.bib
biblio-style: authoryear-comp
fig-width: 8
fig-height: 5
fig-align: center
output-width: 100%
highlight-style: tango

execute:
  freeze: auto
  collapse: true
  echo: true
  cache: true

format:
  html:
    theme:
      - cosmo
      - otexts.scss
    fontsize: 18px
    linestretch: 1.5
    mainfont: "Noto Serif, Georgia, serif"
    code-link: false
    code-fold: true
    embed-resources: false
