project:
  type: book

book:
  title: "That's weird! Anomaly&nbsp;detection using&nbsp;R"
  author:
    name: "<a href='https://robjhyndman.com'>Rob J Hyndman</a>"
    affiliation: "Monash University, Australia"
  site-url: "https://OTexts.com/weird"
  chapters:
    - index.qmd
    - "01-intro.qmd"
    - "02-tools.qmd"
    - "03-parametric.qmd"
    - "04-quantile.qmd"
    - "05-density.qmd"
    - "06-distance.qmd"
    - "07-highdim.qmd"
    - "08-non-euclidean.qmd"
    - "09-modelling.qmd"
    - "10-timeseries.qmd"
    - "11-functional.qmd"
    - "12-network.qmd"
    - "13-imagevideo.qmd"
    - "14-text.qmd"
    - "15-distributions.qmd"
    - "16-deeplearning.qmd"
    - "17-cybersecurity.qmd"
    - "99-refs.qmd"
  page-footer:
    left: "Published by OTexts using <a href='https://quarto.org'>Quarto</a>. © 2022, <a href='https://robjhyndman.com'>Rob J Hyndman</a>"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"
  favicon: "https://otexts.com/favicon.ico"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
include-before-body: google_analytics.html
bibliography: weird.bib
biblio-style: authoryear-comp

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - otexts.scss
    fontsize: 16px
    mainfont: "Merriweather, Georgia, serif"
    code-link: true
